--liquibase formatted sql

--changeset DartAxis:001
create table public.users(id bigint generated by default as identity primary key not null,
                          created timestamp default current_timestamp not null,
                          updated timestamp default current_timestamp not null,
                          status varchar(25) not null default 'ACTIVE',
                          username varchar(100) unique not null,
                          firstname varchar(100),
                          lastname varchar(100),
                          email varchar(100),
                          password varchar(255) not null);

--changeset DartAxis:002
create table public.roles(id bigint generated by default as identity primary key not null,
                          created timestamp default current_timestamp not null,
                          updated timestamp default current_timestamp not null,
                          status varchar not null default 'ACTIVE',
                          name varchar not null unique);

--changeset DartAxis:003
create table public.user_roles(user_id bigint not null, role_id bigint not null,
                                constraint users_id foreign key(user_id) references public.users(id),
                                constraint roles_id foreign key(role_id) references public.roles(id));
--changeset DartAxis:004
insert into public.roles(name) values ('ROLE_USER'),('ROLE_ADMIN'),('ROLE_MODERATOR');

--changeset DartAxis:005
insert into public.users(username,firstname,lastname,password) values ('dart_admin','Алексей','Филатьев','$2a$12$noC.vPRUh2lKe0S7dFg6tuElEfqiv2b24K9gx3CuufPMb1Yo3zFm6')

--changeset DartAxis:006
insert into public.user_roles(user_id,role_id) values(1,2)
